server:
  port: 80
spring:
  main:
    allow-circular-references: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/news_status_project
    password: root123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-request-size: 1000000MB
      max-file-size: 1000000MB